// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedZone.LumiaroAdmin.Data;

#nullable disable

namespace LumiaroAdmin.Data.Migrations
{
    [DbContext(typeof(LumiaroDbContext))]
    partial class LumiaroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.AssessmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("FixtureId")
                        .HasColumnType("int");

                    b.Property<string>("KmiPanelNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("OfficialRole")
                        .HasColumnType("int");

                    b.Property<decimal>("OverallScore")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("Recommendations")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("RefereeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SummaryNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("RefereeId");

                    b.HasIndex("Status");

                    b.HasIndex("FixtureId", "RefereeId", "OfficialRole")
                        .IsUnique()
                        .HasDatabaseName("IX_Assessments_Fixture_Referee_Role");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.CareerEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RefereeId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RefereeId", "SortOrder");

                    b.ToTable("RefereeCareerEntries");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.DelegateReportEntity", b =>
                {
                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<string>("CommunicationAreasForImprovement")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CommunicationNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("CommunicationScore")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("CommunicationStrengths")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ConsistencyAreasForImprovement")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ConsistencyNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("ConsistencyScore")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("ConsistencyStrengths")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DelegateName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ManagementAreasForImprovement")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ManagementNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("ManagementScore")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("ManagementStrengths")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OverallNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("AssessmentId");

                    b.ToTable("DelegateReports");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.DivisionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.FixtureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("KickOff")
                        .HasColumnType("time");

                    b.Property<int>("Matchday")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Venue")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Matchday");

                    b.HasIndex("DivisionId", "Date");

                    b.HasIndex("HomeTeam", "AwayTeam", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_Fixtures_Match_Unique");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.KeyMatchIncidentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<int>("DecisionType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Minute")
                        .HasColumnType("int");

                    b.Property<bool>("OriginalDecisionCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("PanelVotesCorrect")
                        .HasColumnType("int");

                    b.Property<int>("PanelVotesIncorrect")
                        .HasColumnType("int");

                    b.Property<string>("Rationale")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<bool>("VarInterventionMade")
                        .HasColumnType("bit");

                    b.Property<bool>("VarInterventionRequired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId", "Minute");

                    b.HasIndex("AssessmentId", "SortOrder");

                    b.ToTable("KeyMatchIncidents");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.MatchEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AssessmentScore")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("Assistants")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Competition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CompetitionTier")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("FixtureId")
                        .HasColumnType("int");

                    b.Property<string>("FourthOfficial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("RedCards")
                        .HasColumnType("int");

                    b.Property<int?>("RefereeId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("FixtureId");

                    b.HasIndex("RefereeId");

                    b.HasIndex("RefereeId", "Date");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.MatchIncidentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IncidentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int?>("Minute")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchIncidents");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.MatchStatReportEntity", b =>
                {
                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<decimal>("AvgSprintSpeedKmh")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal>("DistanceCoveredKm")
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("FoulsGiven")
                        .HasColumnType("int");

                    b.Property<int>("HighIntensityRuns")
                        .HasColumnType("int");

                    b.Property<string>("IncidentNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("OffsidesCalled")
                        .HasColumnType("int");

                    b.Property<int>("PenaltiesAwarded")
                        .HasColumnType("int");

                    b.Property<int>("RedCards")
                        .HasColumnType("int");

                    b.Property<string>("VarInteractionNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId");

                    b.ToTable("MatchStatReports");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.OfficialAssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("FixtureId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RefereeId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId", "RefereeId")
                        .IsUnique()
                        .HasDatabaseName("IX_OfficialAssignments_Fixture_Referee");

                    b.HasIndex("FixtureId", "Role")
                        .IsUnique()
                        .HasDatabaseName("IX_OfficialAssignments_Fixture_Role");

                    b.HasIndex("RefereeId", "FixtureId");

                    b.ToTable("OfficialAssignments");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.RefereeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccuracyPercent")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal>("AverageScore")
                        .HasColumnType("decimal(4,1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentSeasonAvgScore")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("CurrentSeasonIncidents")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSeasonMatches")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSeasonPenalties")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSeasonReds")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSeasonYellows")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RefCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeasons")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RefCode")
                        .IsUnique();

                    b.HasIndex("Region");

                    b.HasIndex("Status");

                    b.HasIndex("Tier");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Referees");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.SeasonStatsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgScore")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("Matches")
                        .HasColumnType("int");

                    b.Property<int>("Penalties")
                        .HasColumnType("int");

                    b.Property<int>("Reds")
                        .HasColumnType("int");

                    b.Property<int>("RefereeId")
                        .HasColumnType("int");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<decimal>("TrendChange")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("Yellows")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RefereeId", "Season");

                    b.ToTable("RefereeSeasonStats");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.TechnicalReportEntity", b =>
                {
                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<string>("ControlAreasForImprovement")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ControlNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("ControlScore")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("ControlStrengths")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FitnessAreasForImprovement")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FitnessNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("FitnessScore")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("FitnessStrengths")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LawAreasForImprovement")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LawNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("LawScore")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("LawStrengths")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OverallNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PositioningAreasForImprovement")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PositioningNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("PositioningScore")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("PositioningStrengths")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("AssessmentId");

                    b.ToTable("TechnicalReports");
                });

            modelBuilder.Entity("RedZone.LumiaroAdmin.Data.Entities.ActivityLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HighlightColor")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("HighlightName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HighlightValue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IconType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("ActivityLog");
                });

            modelBuilder.Entity("RedZone.LumiaroAdmin.Data.Entities.InterventionReviewEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccuracyScore")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("CommunicationScore")
                        .HasColumnType("int");

                    b.Property<int>("ConsistencyScore")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("MatchHandlingScore")
                        .HasColumnType("int");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ReviewerRole")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ReportId");

                    b.HasIndex("ReportId", "EventId");

                    b.HasIndex("ReportId", "ReviewerName");

                    b.ToTable("InterventionReviews");
                });

            modelBuilder.Entity("RedZone.LumiaroAdmin.Data.Entities.MatchOfficialReportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AuthorRole")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("CompetitionTier")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DevelopmentPriorities")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ExecutiveSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("FixtureId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("date");

                    b.Property<string>("MatchTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("OfficialRole")
                        .HasColumnType("int");

                    b.Property<decimal>("OverallRating")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("RefereeCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RefereeId")
                        .HasColumnType("int");

                    b.Property<string>("RefereeInitials")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("RefereeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RefereeTier")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("MatchDate");

                    b.HasIndex("RefereeId");

                    b.HasIndex("Status");

                    b.HasIndex("FixtureId", "RefereeId", "OfficialRole")
                        .IsUnique()
                        .HasDatabaseName("IX_Reports_Fixture_Referee_Role");

                    b.ToTable("MatchOfficialReports");
                });

            modelBuilder.Entity("RedZone.LumiaroAdmin.Data.Entities.ReportEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int?>("AddedTime")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<int>("Impact")
                        .HasColumnType("int");

                    b.Property<int>("Minute")
                        .HasColumnType("int");

                    b.Property<bool>("OfficialInvolved")
                        .HasColumnType("bit");

                    b.Property<string>("OfficialResponse")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("Teams")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId", "Minute");

                    b.ToTable("ReportEvents");
                });

            modelBuilder.Entity("RedZone.LumiaroAdmin.Data.Entities.ReportSectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreasForImprovement")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Narrative")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Strengths")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId", "SortOrder");

                    b.ToTable("ReportSections");
                });

            modelBuilder.Entity("RedZone.LumiaroAdmin.Data.Entities.VideoClipEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Timestamp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId", "SortOrder");

                    b.ToTable("VideoClips");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.AssessmentEntity", b =>
                {
                    b.HasOne("LumiaroAdmin.Data.Entities.FixtureEntity", "Fixture")
                        .WithMany("Assessments")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LumiaroAdmin.Data.Entities.RefereeEntity", "Referee")
                        .WithMany("Assessments")
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fixture");

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.CareerEntryEntity", b =>
                {
                    b.HasOne("LumiaroAdmin.Data.Entities.RefereeEntity", "Referee")
                        .WithMany("CareerHistory")
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.DelegateReportEntity", b =>
                {
                    b.HasOne("LumiaroAdmin.Data.Entities.AssessmentEntity", "Assessment")
                        .WithOne("DelegateReport")
                        .HasForeignKey("LumiaroAdmin.Data.Entities.DelegateReportEntity", "AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.FixtureEntity", b =>
                {
                    b.HasOne("LumiaroAdmin.Data.Entities.DivisionEntity", "Division")
                        .WithMany("Fixtures")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.KeyMatchIncidentEntity", b =>
                {
                    b.HasOne("LumiaroAdmin.Data.Entities.AssessmentEntity", "Assessment")
                        .WithMany("KeyMatchIncidents")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.MatchEntity", b =>
                {
                    b.HasOne("LumiaroAdmin.Data.Entities.FixtureEntity", "Fixture")
                        .WithMany()
                        .HasForeignKey("FixtureId");

                    b.HasOne("LumiaroAdmin.Data.Entities.RefereeEntity", "Referee")
                        .WithMany()
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Fixture");

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.MatchIncidentEntity", b =>
                {
                    b.HasOne("LumiaroAdmin.Data.Entities.MatchEntity", "Match")
                        .WithMany("Incidents")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.MatchStatReportEntity", b =>
                {
                    b.HasOne("LumiaroAdmin.Data.Entities.AssessmentEntity", "Assessment")
                        .WithOne("MatchStatReport")
                        .HasForeignKey("LumiaroAdmin.Data.Entities.MatchStatReportEntity", "AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.OfficialAssignmentEntity", b =>
                {
                    b.HasOne("LumiaroAdmin.Data.Entities.FixtureEntity", "Fixture")
                        .WithMany("OfficialAssignments")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LumiaroAdmin.Data.Entities.RefereeEntity", "Referee")
                        .WithMany("Assignments")
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fixture");

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.SeasonStatsEntity", b =>
                {
                    b.HasOne("LumiaroAdmin.Data.Entities.RefereeEntity", "Referee")
                        .WithMany("SeasonBreakdown")
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.TechnicalReportEntity", b =>
                {
                    b.HasOne("LumiaroAdmin.Data.Entities.AssessmentEntity", "Assessment")
                        .WithOne("TechnicalReport")
                        .HasForeignKey("LumiaroAdmin.Data.Entities.TechnicalReportEntity", "AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("RedZone.LumiaroAdmin.Data.Entities.InterventionReviewEntity", b =>
                {
                    b.HasOne("RedZone.LumiaroAdmin.Data.Entities.ReportEventEntity", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RedZone.LumiaroAdmin.Data.Entities.MatchOfficialReportEntity", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("RedZone.LumiaroAdmin.Data.Entities.MatchOfficialReportEntity", b =>
                {
                    b.HasOne("LumiaroAdmin.Data.Entities.FixtureEntity", "Fixture")
                        .WithMany()
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LumiaroAdmin.Data.Entities.RefereeEntity", "Referee")
                        .WithMany()
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("RedZone.LumiaroAdmin.Data.Entities.ReportEventEntity", b =>
                {
                    b.HasOne("RedZone.LumiaroAdmin.Data.Entities.MatchOfficialReportEntity", "Report")
                        .WithMany("Events")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("RedZone.LumiaroAdmin.Data.Entities.ReportSectionEntity", b =>
                {
                    b.HasOne("RedZone.LumiaroAdmin.Data.Entities.MatchOfficialReportEntity", "Report")
                        .WithMany("Sections")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("RedZone.LumiaroAdmin.Data.Entities.VideoClipEntity", b =>
                {
                    b.HasOne("RedZone.LumiaroAdmin.Data.Entities.MatchOfficialReportEntity", "Report")
                        .WithMany("VideoClips")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.AssessmentEntity", b =>
                {
                    b.Navigation("DelegateReport");

                    b.Navigation("KeyMatchIncidents");

                    b.Navigation("MatchStatReport");

                    b.Navigation("TechnicalReport");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.DivisionEntity", b =>
                {
                    b.Navigation("Fixtures");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.FixtureEntity", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("OfficialAssignments");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.MatchEntity", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("LumiaroAdmin.Data.Entities.RefereeEntity", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Assignments");

                    b.Navigation("CareerHistory");

                    b.Navigation("SeasonBreakdown");
                });

            modelBuilder.Entity("RedZone.LumiaroAdmin.Data.Entities.MatchOfficialReportEntity", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Sections");

                    b.Navigation("VideoClips");
                });
#pragma warning restore 612, 618
        }
    }
}
